#ifndef EDIT_DEF
#define EDIT_DEF

enum {
	ENEMOVE_FLATY,
	ENEMOVE_FLATMOVE,
	ENEMOVE_MOVEWAITY,
	ENEMOVE_MOVEWAITYNOANG,
	ENEMOVE_MOVEWAITYACCEL,
	ENEMOVE_MOVEWAITYACCELNOANG,
	ENEMOVE_MOVEWAITYSLOW,
	ENEMOVE_MOVEWAITYSLOWNOANG,
	ENEMOVE_TOWARDCENTER,
	ENEMOVE_TOWARDEDGE,
	ENEMOVE_ACCELTURN,
	ENEMOVE_TURNRIGHTANGLE,
	ENEMOVE_TURNLEFTANGLE,
	ENEMOVE_TURN90,
	ENEMOVE_LASERSHOT,
	ENEMOVE_LASERSHOTWAIT,
	ENEMOVE_TIMERBOMB,
	ENEMOVE_MOVECIRCLE,
	ENEMOVE_MOVEHEXFLAT,
	ENEMOVE_MOVEHEXCLOCK,
	ENEMOVE_THUNDER,
	ENEMOVE_RUSH,
	ENEMOVE_MADNESS,
	ENEMOVE_MOVEHEADFLATMOVE,
	ENEMOVE_MOVEHEXSQ,
	ENEMOVE_MOVESQ,
	ENEMOVE_NUM
};
//移動

enum {
	ENESHOT_FLATMOVE,		 //水平に発射
	ENESHOT_FLATMOVE5,		 //水平に発射
	ENESHOT_TOWARDMYCHAR,//マイキャラに向けて発射
	ENESHOT_TOWARDMYCHAR3,
	ENESHOT_TOWARDMYCHAR5,
	ENESHOT_FRONTRANDOM, //前方に向けてランダムに発射
	ENESHOT_FRONTRANDOM5,
	ENESHOT_MYCHARRANDOM5,
	ENESHOT_MYCHARRANDOM3,
	ENESHOT_FRONT3WAY,	//前方に向けて３発拡散発射
	ENESHOT_FRONT5WAY,	//前方に向けて５発拡散発射
	ENESHOT_FRONT7WAYHORM,
	ENESHOT_ALLRANGE30,
	ENESHOT_ALLRANGE15,
	ENESHOT_ALLRANGERAND16,
	ENESHOT_SPIRAL,
	ENESHOT_ALLRANGERAND30,
	ENESHOT_LASER,
	ENESHOT_NBOMBFLAME,
	ENESHOT_TBOMBFLAME,
	ENESHOT_HEXSHOT,
	ENESHOT_TRISHOT,
	ENESHOT_THUNDER,
	ENESHOT_NUM
};

//弾発射

enum {
	SHOTOPE_FLATMOVE,
	SHOTOPE_SLOW,
	SHOTOPE_ACCEL,
	SHOTOPE_TOWARDMYCHAR,
	SHOTOPE_TOWARDMYCHARACCEL,
	SHOTOPE_TOWARDMYCHARACCELNOADJ,
	SHOTOPE_TOWARDMYCHARNOADJ,
	SHOTOPE_FLASH,
	SHOTOPE_BOMB,
	SHOTOPE_CHARGESHOT,
	SHOTOPE_LASER,
	SHOTOPE_ROLLSPIRAL,
	SHOTOPE_SPLITSHOT,
	SHOTOPE_MATHSHOT,
	SHOTOPE_ST2BOSS,
	SHTOPE_NUM
};
//弾移動

enum {
	ENEMY_ZAKOWK,
	ENEMY_ZAKOWK2,
	ENEMY_ZAKOWK3,
	ENEMY_ZAKOWK4,
	ENEMY_ZAKOWK5,
	ENEMY_ZAKOST,
	ENEMY_ZAKOCN,
	ENEMY_ZAKOCN2,
	ENEMY_ZAKOCN3,
	ENEMY_ZAKOHEX,
	ENEMY_ZAKOHEX2,
	ENEMY_ZAKOHEAD,

	ENEMY_MIDBOSS,
	ENEMY_STOPZAKO,
	ENEMY_STOPZAKO2,
	ENEMY_BOMB,
	ENEMY_SHOTM,
	ENEMY_SATEBOX,
	ENEMY_TIMER,
	ENEMY_S2BOSS,
	ST2GIM_D2,
	ENEMY_RUSH,
	ENEMY_MAD,
	ENEMY_GOAST,
	ENEMYDATA_NUM
};

//敵データ

enum {
	SHOT_NSHOT1,
	SHOT_NSHOT2_1,
	SHOT_NSHOT2_2,
	SHOT_NSHOT3_1,
	SHOT_NSHOT3_2,
	SHOT_NSHOT3_REV,
	SHOT_SATEBAR,
	SHOT_BOMB,
	SHOT_CHARGESHOT,
	SHOT_CSHOTBURN1,
	SHOT_CSHOTBURN2,
	SHOT_CSHOTBURN3,
	SHOT_SATEATKSHOT,
	SHOT_ENESQ,
	SHOT_ENELASER,
	SHOT_ENESMALL,
	SHOT_ENEEN,
	SHOT_ENESP,
	SHOT_SATEATKSMASH,
	SHOT_SATEGRDSMASH,
	SHOT_ENEBIGLASER,
	SHOT_ENEFLAME,
	SHOT_ST2BOSS,
	SHOT_ENECOUNTERSHOT,
	SHOT_ENELASEN,
	SHOT_THUNDER,
	SHOT_ENELASENF,
	SHOTDATA_NUM
};
//弾データ

#endif