#ifndef SHT_OPE_DEF
#define SHT_OPE_DEF

#include "shot.h"

class MyCharacter;

enum {
	SHOTOPE_FLATMOVE,
	SHOTOPE_SLOW,
	SHOTOPE_ACCEL,
	SHOTOPE_TOWARDMYCHAR,
	SHOTOPE_TOWARDMYCHARACCEL,
	SHOTOPE_TOWARDMYCHARACCELNOADJ,
	SHOTOPE_TOWARDMYCHARNOADJ,
	SHOTOPE_FLASH,
	SHOTOPE_BOMB,
	SHOTOPE_CHARGESHOT,
	SHOTOPE_LASER,
	SHOTOPE_ROLLSPIRAL,
	SHOTOPE_SPLITSHOT,
	SHOTOPE_MATHSHOT,
	SHOTOPE_ST2BOSS,
	SHOTOPE_NOMOVE,
	SHTOPE_NUM
};

extern int (*Shot_Operate[SHTOPE_NUM])(Shot* shot, ShotMgr* sht_mgr, MyCharacter* mychar);
					//関数ポインタ配列の宣言
#endif